### ISSUE TITLE
SkyFactory 4

### ISSUE THREAD

**Issue by MineKing9534** [CustomCheat/LinuxCurse#4]
I'm getting this error with `SkyFactory 4`:
```
No modpacks found!! Try using some parts of the modpack like Better Minecraft [FABRIC] - 1.17.1 use Better Minecraft if this is still happening make a issue on the github page with the modpack name
No modpacks found!! Try using some parts of the modpack like Better Minecraft [FABRIC] - 1.17.1 use Better Minecraft if this is still happening make a issue on the github page with the modpack name
Please specify the name more if u think this is an issue report it on the github issue page
```

**Comment by CustomCheat** [comment]
As the output says: Try using some parts of the modpack so just instead of Skyfactory 4 enter just Skyfactory then it will say more options just select the right one in your case Skyfactory 4, the search did go through some modifications because not all modpacks did get detected while this search isn't the best it works, it uses the API but it isn't implemented that good in the code

**Comment by MineKing9534** [comment]
That's working, thanks :smiley:

**Comment by CustomCheat** [comment]
Closing this issue now
